# Generated by Django 3.0.8 on 2020-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20200919_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userumg',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userumg',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userumg',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
