# Generated by Django 3.0.8 on 2020-09-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20200919_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('consejero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.UserUmg')),
            ],
        ),
        migrations.CreateModel(
            name='Dormitorio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(null=True, unique=True)),
                ('habitacion', models.IntegerField(null=True)),
                ('residente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.UserUmg')),
            ],
        ),
    ]
